services:
  account-sso:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:22-bookworm-slim}
        NPM_REGISTRY: ${NPM_REGISTRY:-https://registry.npmmirror.com}
        PRISMA_ENGINES_MIRROR: ${PRISMA_ENGINES_MIRROR:-https://npmmirror.com/mirrors/prisma}
        DEBIAN_MIRROR: ${DEBIAN_MIRROR:-http://mirrors.aliyun.com/debian}
        DEBIAN_SECURITY_MIRROR: ${DEBIAN_SECURITY_MIRROR:-http://mirrors.aliyun.com/debian-security}
    image: account-shifuf-sso:latest
    container_name: account-shifuf-sso
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      NODE_ENV: production
      PORT: 8086
      DATABASE_URL: file:/app/data/prod.db
      FRONTEND_DIST_DIR: /app/frontend-dist
      FRONTEND_URL: ${FRONTEND_URL}
      OIDC_ISSUER: ${OIDC_ISSUER}
      OAUTH_CALLBACK_BASE_URL: ${OAUTH_CALLBACK_BASE_URL}
      JWT_ACCESS_TOKEN_EXPIRES_IN: ${JWT_ACCESS_TOKEN_EXPIRES_IN}
      JWT_REFRESH_TOKEN_EXPIRES_IN: ${JWT_REFRESH_TOKEN_EXPIRES_IN}
      JWT_KEY_ID: ${JWT_KEY_ID}
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
      ENABLE_DEBUG_EMAIL_CODE: ${ENABLE_DEBUG_EMAIL_CODE}
      BACKUP_DIR: /app/backend/backups
      AUTO_BACKUP_ENABLED: ${AUTO_BACKUP_ENABLED}
      AUTO_BACKUP_INTERVAL_HOURS: ${AUTO_BACKUP_INTERVAL_HOURS}
      AUTO_BACKUP_RETENTION_COUNT: ${AUTO_BACKUP_RETENTION_COUNT}
      AUTO_BACKUP_COMPRESS: ${AUTO_BACKUP_COMPRESS}
      OIDC_PRIVATE_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDautJQW5BgcxJA
        HX68kIrd4YtEZsnfPAcPCVSZa2Ny9gznZp3bXO7LtGDmwzlN/hhAJ9qknK0zB5Ai
        HVgbfkyVqGyHARdg3sbRjkr1MsGb1jDS1g+/XuwQSbck1Oyvl72SnGyhY6Uhzkh+
        58qEFgQvTDEIVdtvC5aRIEin7Swpof2YYv7ciR2+iafPoYgKgVOUctR2qKFOBBQL
        JtknN2X5ei9HrvRBnkEdtIhQ4Ram7sCzdZjAcv8+lKeTTtpBOCy19AE0r0AhaLyq
        mOuO9wj1qhP3IEbTMSiIGfI1lPscdibGnVZFF5dImVkf/6h2DicjbP6WJHoDKx+H
        TDbLA/6FAgMBAAECggEADaYRwJzuFe6oSWLtySN13uGXmKWXXDw5LomFA2vNkVtk
        M75WBF24svJnB49QEJtV9Q7nmFUEg8Ypis9s844+hioz13rMdCmCm4n3CHTp2ukT
        M9zSr7zjGyMWcBBvUoez9yWWq711jPX71Rtuqi5bhX4KIzyETFobQ6QRlJT6qABL
        tANnOtuDqv+gRRlLTgNcxStRgZ++TAtPVY/Bpo/ja9uJ/JyC1VczsmZ76MTddYqh
        looORJDF/2IN6qBSpsfGCVdweGZRo1f72AOAnPtFOejFHf6tn8hqo1kzKO1a4cvg
        rvBO7eDoCHxpVYWTYGodpJHlsVY5oHOYXRgPbr30QwKBgQDtlR2bVLC6iSicTv2Q
        Ijoy1wwDq7Ld0lKCU+FUYlCK0/hfH79O1uWBxqp06mvMddleZYQfO3DDwNbBg9Tg
        vvFcoEnW8Z8LJqOkhgfAJbgFMZC5jciIBZOy+yr1g59rdNMZPyFtc2cMxcZmDgku
        E8saU/JvFn6SMSxjtp58k9ylhwKBgQDrr5Guoi8uD5T8Tt65Ue9gjtJ5uIJF1AvA
        TECXX1z7ZqzsKOgTObRE66uQDQyUAJA6IuWv0SB+xpKns0Ctyd0YERCu64gFDLJt
        j07+f0HRlNY2tppn+vc7SQX96GtymWkeUT4ByNeTyFAQxxmCPZxIJJyBFgxSAk7P
        TZGuZYP+kwKBgEP4y5WrLzzPDP1bZBQelsQA3oEWWIA6MjzzPp5j2mM9reuZK6Sk
        utjcO9xjTSAb/2qQZLKC0QpQW6DV1MvQFUHI4hdK3ZPVJDBn4EPLBtEFk0BjHiI8
        ZjtovKutUqjtrY+ljizAPZVb6B0+msXCB/OqXMwHhYLR6r9EeiduLkx1AoGAQwpz
        9CrqJL4F8Sc2L5zg7KRztnAHjnlcxlxqWySjPFfehGa2bRGS96/Z42Xy1/65B/B5
        SWPBTI6LlOxmT4kGPRxNlJQm4tjTwFpta/Mi88zUikey8DTxMon5DFqahcShpCAT
        9Un+GGl4bO1VkjiYReU0J3vwETva0xkLgYIa48UCgYEA6tLvg7jhSz8pbLQHJ5fk
        BwVPJFrnJM6vsnUMXbnOC8dF31q9l4Hhxe4Dr1gWifvfyGtwzLRykgJrc5oCvz5L
        dbxrb5b5eltTC6hsPqkmXV5dw6bL+tJPGGv6WXSLCJi5S4nZp5Q075Fits2ZoCrQ
        l5L4umExupYJdWM2Jfg1bww=
        -----END PRIVATE KEY-----
      OIDC_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2rrSUFuQYHMSQB1+vJCK
        3eGLRGbJ3zwHDwlUmWtjcvYM52ad21zuy7Rg5sM5Tf4YQCfapJytMweQIh1YG35M
        lahshwEXYN7G0Y5K9TLBm9Yw0tYPv17sEEm3JNTsr5e9kpxsoWOlIc5IfufKhBYE
        L0wxCFXbbwuWkSBIp+0sKaH9mGL+3Ikdvomnz6GICoFTlHLUdqihTgQUCybZJzdl
        +XovR670QZ5BHbSIUOEWpu7As3WYwHL/PpSnk07aQTgstfQBNK9AIWi8qpjrjvcI
        9aoT9yBG0zEoiBnyNZT7HHYmxp1WRReXSJlZH/+odg4nI2z+liR6Aysfh0w2ywP+
        hQIDAQAB
        -----END PUBLIC KEY-----
    volumes:
      - ./docker-data/data:/app/data
      - ./docker-data/uploads:/app/backend/uploads
      - ./docker-data/backups:/app/backend/backups
